# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:12:00+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Accelerator(BaseModel):
    count: Optional[str] = Field(
        None, description='How many accelerators of this type to attach.'
    )
    type: Optional[str] = Field(
        None,
        description='The accelerator type string (for example, "nvidia-tesla-k80"). Only NVIDIA GPU accelerators are currently supported. If an NVIDIA GPU is attached, the required runtime libraries will be made available to all containers under `/usr/local/nvidia`. The driver version to install must be specified using the NVIDIA driver version parameter on the virtual machine specification. Note that attaching a GPU increases the worker VM startup time by a few minutes.',
    )


class Flag(Enum):
    FLAG_UNSPECIFIED = 'FLAG_UNSPECIFIED'
    IGNORE_EXIT_STATUS = 'IGNORE_EXIT_STATUS'
    RUN_IN_BACKGROUND = 'RUN_IN_BACKGROUND'
    ALWAYS_RUN = 'ALWAYS_RUN'
    ENABLE_FUSE = 'ENABLE_FUSE'
    PUBLISH_EXPOSED_PORTS = 'PUBLISH_EXPOSED_PORTS'
    DISABLE_IMAGE_PREFETCH = 'DISABLE_IMAGE_PREFETCH'
    DISABLE_STANDARD_ERROR_CAPTURE = 'DISABLE_STANDARD_ERROR_CAPTURE'
    BLOCK_EXTERNAL_NETWORK = 'BLOCK_EXTERNAL_NETWORK'


class CancelOperationRequest(BaseModel):
    pass


class CheckInResponse(BaseModel):
    deadline: Optional[str] = Field(
        None,
        description='The deadline by which the worker must request an extension. The backend will allow for network transmission time and other delays, but the worker must attempt to transmit the extension request no later than the deadline.',
    )
    features: Optional[Dict[str, Any]] = Field(
        None, description='Feature configuration for the operation.'
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='The metadata that describes the operation assigned to the worker.',
    )


class ContainerKilledEvent(BaseModel):
    actionId: Optional[int] = Field(
        None, description='The numeric ID of the action that started the container.'
    )


class ContainerStartedEvent(BaseModel):
    actionId: Optional[int] = Field(
        None, description='The numeric ID of the action that started this container.'
    )
    ipAddress: Optional[str] = Field(
        None,
        description='The public IP address that can be used to connect to the container. This field is only populated when at least one port mapping is present. If the instance was created with a private address, this field will be empty even if port mappings exist.',
    )
    portMappings: Optional[Dict[str, int]] = Field(
        None,
        description='The container-to-host port mappings installed for this container. This set will contain any ports exposed using the `PUBLISH_EXPOSED_PORTS` flag as well as any specified in the `Action` definition.',
    )


class ContainerStoppedEvent(BaseModel):
    actionId: Optional[int] = Field(
        None, description='The numeric ID of the action that started this container.'
    )
    exitStatus: Optional[int] = Field(
        None, description='The exit status of the container.'
    )
    stderr: Optional[str] = Field(
        None,
        description='The tail end of any content written to standard error by the container. If the content emits large amounts of debugging noise or contains sensitive information, you can prevent the content from being printed by setting the `DISABLE_STANDARD_ERROR_CAPTURE` flag. Note that only a small amount of the end of the stream is captured here. The entire stream is stored in the `/google/logs` directory mounted into each action, and can be copied off the machine as described elsewhere.',
    )


class DelayedEvent(BaseModel):
    cause: Optional[str] = Field(
        None,
        description='A textual description of the cause of the delay. The string can change without notice because it is often generated by another service (such as Compute Engine).',
    )
    metrics: Optional[List[str]] = Field(
        None,
        description='If the delay was caused by a resource shortage, this field lists the Compute Engine metrics that are preventing this operation from running (for example, `CPUS` or `INSTANCES`). If the particular metric is not known, a single `UNKNOWN` metric will be present.',
    )


class Disk(BaseModel):
    name: Optional[str] = Field(
        None,
        description='A user-supplied name for the disk. Used when mounting the disk into actions. The name must contain only upper and lowercase alphanumeric characters and hyphens and cannot start with a hyphen.',
    )
    sizeGb: Optional[int] = Field(
        None,
        description='The size, in GB, of the disk to attach. If the size is not specified, a default is chosen to ensure reasonable I/O performance. If the disk type is specified as `local-ssd`, multiple local drives are automatically combined to provide the requested size. Note, however, that each physical SSD is 375GB in size, and no more than 8 drives can be attached to a single instance.',
    )
    sourceImage: Optional[str] = Field(
        None,
        description='An optional image to put on the disk before attaching it to the VM.',
    )
    type: Optional[str] = Field(
        None,
        description='The Compute Engine disk type. If unspecified, `pd-standard` is used.',
    )


class DiskStatus(BaseModel):
    freeSpaceBytes: Optional[str] = Field(None, description='Free disk space.')
    totalSpaceBytes: Optional[str] = Field(None, description='Total disk space.')


class Empty(BaseModel):
    pass


class Event(BaseModel):
    description: Optional[str] = Field(
        None,
        description='A human-readable description of the event. Note that these strings can change at any time without notice. Any application logic must use the information in the `details` field.',
    )
    details: Optional[Dict[str, Any]] = Field(
        None, description='Machine-readable details about the event.'
    )
    timestamp: Optional[str] = Field(
        None, description='The time at which the event occurred.'
    )


class ExistingDisk(BaseModel):
    disk: Optional[str] = Field(
        None,
        description='If `disk` contains slashes, the Cloud Life Sciences API assumes that it is a complete URL for the disk. If `disk` does not contain slashes, the Cloud Life Sciences API assumes that the disk is a zonal disk and a URL will be generated of the form `zones//disks/`, where `` is the zone in which the instance is allocated. The disk must be ext4 formatted. If all `Mount` references to this disk have the `read_only` flag set to true, the disk will be attached in `read-only` mode and can be shared with other instances. Otherwise, the disk will be available for writing but cannot be shared.',
    )


class Code(Enum):
    OK = 'OK'
    CANCELLED = 'CANCELLED'
    UNKNOWN = 'UNKNOWN'
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    DEADLINE_EXCEEDED = 'DEADLINE_EXCEEDED'
    NOT_FOUND = 'NOT_FOUND'
    ALREADY_EXISTS = 'ALREADY_EXISTS'
    PERMISSION_DENIED = 'PERMISSION_DENIED'
    UNAUTHENTICATED = 'UNAUTHENTICATED'
    RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED'
    FAILED_PRECONDITION = 'FAILED_PRECONDITION'
    ABORTED = 'ABORTED'
    OUT_OF_RANGE = 'OUT_OF_RANGE'
    UNIMPLEMENTED = 'UNIMPLEMENTED'
    INTERNAL = 'INTERNAL'
    UNAVAILABLE = 'UNAVAILABLE'
    DATA_LOSS = 'DATA_LOSS'


class FailedEvent(BaseModel):
    cause: Optional[str] = Field(
        None, description='The human-readable description of the cause of the failure.'
    )
    code: Optional[Code] = Field(
        None,
        description='The Google standard error code that best describes this failure.',
    )


class Mount(BaseModel):
    disk: Optional[str] = Field(
        None,
        description='The name of the disk to mount, as specified in the resources section.',
    )
    path: Optional[str] = Field(
        None, description='The path to mount the disk inside the container.'
    )
    readOnly: Optional[bool] = Field(
        None, description='If true, the disk is mounted read-only inside the container.'
    )


class NFSMount(BaseModel):
    target: Optional[str] = Field(
        None,
        description='A target NFS mount. The target must be specified as `address:/mount".',
    )


class Network(BaseModel):
    name: Optional[str] = Field(
        None,
        description="The network name to attach the VM's network interface to. The value will be prefixed with `global/networks/` unless it contains a `/`, in which case it is assumed to be a fully specified network resource URL. If unspecified, the global default network is used.",
    )
    subnetwork: Optional[str] = Field(
        None,
        description='If the specified network is configured for custom subnet creation, the name of the subnetwork to attach the instance to must be specified here. The value is prefixed with `regions/*/subnetworks/` unless it contains a `/`, in which case it is assumed to be a fully specified subnetwork resource URL. If the `*` character appears in the value, it is replaced with the region that the virtual machine has been allocated in.',
    )
    usePrivateAddress: Optional[bool] = Field(
        None,
        description='If set to true, do not attach a public IP address to the VM. Note that without a public IP address, additional configuration is required to allow the VM to access Google services. See https://cloud.google.com/vpc/docs/configure-private-google-access for more information.',
    )


class PersistentDisk(BaseModel):
    sizeGb: Optional[int] = Field(
        None,
        description='The size, in GB, of the disk to attach. If the size is not specified, a default is chosen to ensure reasonable I/O performance. If the disk type is specified as `local-ssd`, multiple local drives are automatically combined to provide the requested size. Note, however, that each physical SSD is 375GB in size, and no more than 8 drives can be attached to a single instance.',
    )
    sourceImage: Optional[str] = Field(
        None, description='An image to put on the disk before attaching it to the VM.'
    )
    type: Optional[str] = Field(
        None,
        description='The Compute Engine disk type. If unspecified, `pd-standard` is used.',
    )


class PullStartedEvent(BaseModel):
    imageUri: Optional[str] = Field(
        None, description='The URI of the image that was pulled.'
    )


class PullStoppedEvent(BaseModel):
    imageUri: Optional[str] = Field(
        None, description='The URI of the image that was pulled.'
    )


class RunPipelineResponse(BaseModel):
    pass


class Secret(BaseModel):
    cipherText: Optional[str] = Field(
        None,
        description='The value of the cipherText response from the `encrypt` method. This field is intentionally unaudited.',
    )
    keyName: Optional[str] = Field(
        None,
        description='The name of the Cloud KMS key that will be used to decrypt the secret value. The VM service account must have the required permissions and authentication scopes to invoke the `decrypt` method on the specified key.',
    )


class ServiceAccount(BaseModel):
    email: Optional[str] = Field(
        None,
        description='Email address of the service account. If not specified, the default Compute Engine service account for the project will be used.',
    )
    scopes: Optional[List[str]] = Field(
        None,
        description='List of scopes to be enabled for this service account on the VM, in addition to the cloud-platform API scope that will be added by default.',
    )


class Status(BaseModel):
    code: Optional[int] = Field(
        None,
        description='The status code, which should be an enum value of google.rpc.Code.',
    )
    details: Optional[List[Dict[str, Any]]] = Field(
        None,
        description='A list of messages that carry the error details. There is a common set of message types for APIs to use.',
    )
    message: Optional[str] = Field(
        None,
        description='A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.',
    )


class TimestampedEvent(BaseModel):
    data: Optional[Dict[str, Any]] = Field(None, description='The event data.')
    timestamp: Optional[str] = Field(
        None, description='The time when the event happened.'
    )


class UnexpectedExitStatusEvent(BaseModel):
    actionId: Optional[int] = Field(
        None, description='The numeric ID of the action that started the container.'
    )
    exitStatus: Optional[int] = Field(
        None, description='The exit status of the container.'
    )


class Volume(BaseModel):
    existingDisk: Optional[ExistingDisk] = Field(
        None, description='Configuration for a existing disk.'
    )
    nfsMount: Optional[NFSMount] = Field(
        None, description='Configuration for an NFS mount.'
    )
    persistentDisk: Optional[PersistentDisk] = Field(
        None, description='Configuration for a persistent disk.'
    )
    volume: Optional[str] = Field(
        None,
        description='A user-supplied name for the volume. Used when mounting the volume into `Actions`. The name must contain only upper and lowercase alphanumeric characters and hyphens and cannot start with a hyphen.',
    )


class WorkerAssignedEvent(BaseModel):
    instance: Optional[str] = Field(None, description="The worker's instance name.")
    machineType: Optional[str] = Field(
        None, description='The machine type that was assigned for the worker.'
    )
    zone: Optional[str] = Field(None, description='The zone the worker is running in.')


class WorkerReleasedEvent(BaseModel):
    instance: Optional[str] = Field(None, description="The worker's instance name.")
    zone: Optional[str] = Field(None, description='The zone the worker was running in.')


class WorkerStatus(BaseModel):
    attachedDisks: Optional[Dict[str, DiskStatus]] = Field(
        None, description='Status of attached disks.'
    )
    bootDisk: Optional[DiskStatus] = Field(None, description='Status of the boot disk.')
    freeRamBytes: Optional[str] = Field(None, description='Free RAM.')
    totalRamBytes: Optional[str] = Field(None, description='Total RAM.')
    uptimeSeconds: Optional[str] = Field(None, description='System uptime.')


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class Action(BaseModel):
    commands: Optional[List[str]] = Field(
        None,
        description='If specified, overrides the `CMD` specified in the container. If the container also has an `ENTRYPOINT` the values are used as entrypoint arguments. Otherwise, they are used as a command and arguments to run inside the container.',
    )
    credentials: Optional[Secret] = Field(
        None,
        description='If the specified image is hosted on a private registry other than Google Container Registry, the credentials required to pull the image must be specified here as an encrypted secret. The secret must decrypt to a JSON-encoded dictionary containing both `username` and `password` keys.',
    )
    encryptedEnvironment: Optional[Secret] = Field(
        None,
        description='The encrypted environment to pass into the container. This environment is merged with values specified in the google.genomics.v2alpha1.Pipeline message, overwriting any duplicate values. The secret must decrypt to a JSON-encoded dictionary where key-value pairs serve as environment variable names and their values. The decoded environment variables can overwrite the values specified by the `environment` field.',
    )
    entrypoint: Optional[str] = Field(
        None,
        description='If specified, overrides the `ENTRYPOINT` specified in the container.',
    )
    environment: Optional[Dict[str, str]] = Field(
        None,
        description='The environment to pass into the container. This environment is merged with values specified in the google.genomics.v2alpha1.Pipeline message, overwriting any duplicate values. In addition to the values passed here, a few other values are automatically injected into the environment. These cannot be hidden or overwritten. `GOOGLE_PIPELINE_FAILED` will be set to "1" if the pipeline failed because an action has exited with a non-zero status (and did not have the `IGNORE_EXIT_STATUS` flag set). This can be used to determine if additional debug or logging actions should execute. `GOOGLE_LAST_EXIT_STATUS` will be set to the exit status of the last non-background action that executed. This can be used by workflow engine authors to determine whether an individual action has succeeded or failed.',
    )
    flags: Optional[List[Flag]] = Field(
        None, description='The set of flags to apply to this action.'
    )
    imageUri: Optional[str] = Field(
        None,
        description="Required. The URI to pull the container image from. Note that all images referenced by actions in the pipeline are pulled before the first action runs. If multiple actions reference the same image, it is only pulled once, ensuring that the same image is used for all actions in a single pipeline. The image URI can be either a complete host and image specification (e.g., quay.io/biocontainers/samtools), a library and image name (e.g., google/cloud-sdk) or a bare image name ('bash') to pull from the default library. No schema is required in any of these cases. If the specified image is not public, the service account specified for the Virtual Machine must have access to pull the images from GCR, or appropriate credentials must be specified in the google.genomics.v2alpha1.Action.credentials field.",
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='Labels to associate with the action. This field is provided to assist workflow engine authors in identifying actions (for example, to indicate what sort of action they perform, such as localization or debugging). They are returned in the operation metadata, but are otherwise ignored.',
    )
    mounts: Optional[List[Mount]] = Field(
        None,
        description="A list of mounts to make available to the action. In addition to the values specified here, every action has a special virtual disk mounted under `/google` that contains log files and other operational components. - /google/logs All logs written during the pipeline execution. - /google/logs/output The combined standard output and standard error of all actions run as part of the pipeline execution. - /google/logs/action/*/stdout The complete contents of each individual action's standard output. - /google/logs/action/*/stderr The complete contents of each individual action's standard error output. ",
    )
    name: Optional[str] = Field(
        None,
        description='An optional name for the container. The container hostname will be set to this name, making it useful for inter-container communication. The name must contain only upper and lowercase alphanumeric characters and hyphens and cannot start with a hyphen.',
    )
    pidNamespace: Optional[str] = Field(
        None,
        description='An optional identifier for a PID namespace to run the action inside. Multiple actions should use the same string to share a namespace. If unspecified, a separate isolated namespace is used.',
    )
    portMappings: Optional[Dict[str, int]] = Field(
        None,
        description='A map of containers to host port mappings for this container. If the container already specifies exposed ports, use the `PUBLISH_EXPOSED_PORTS` flag instead. The host port number must be less than 65536. If it is zero, an unused random port is assigned. To determine the resulting port number, consult the `ContainerStartedEvent` in the operation metadata.',
    )
    timeout: Optional[str] = Field(
        None,
        description='The maximum amount of time to give the action to complete. If the action fails to complete before the timeout, it will be terminated and the exit status will be non-zero. The pipeline will continue or terminate based on the rules defined by the `ALWAYS_RUN` and `IGNORE_EXIT_STATUS` flags.',
    )


class CheckInRequest(BaseModel):
    deadlineExpired: Optional[Empty] = Field(
        None, description='The deadline has expired and the worker needs more time.'
    )
    event: Optional[Dict[str, Any]] = Field(
        None, description='A workflow specific event occurred.'
    )
    events: Optional[List[TimestampedEvent]] = Field(
        None, description='A list of timestamped events.'
    )
    result: Optional[Status] = Field(
        None, description='The operation has finished with the given result.'
    )
    sosReport: Optional[str] = Field(
        None, description='An SOS report for an unexpected VM failure.'
    )
    workerStatus: Optional[WorkerStatus] = Field(
        None, description='Data about the status of the worker VM.'
    )


class Operation(BaseModel):
    done: Optional[bool] = Field(
        None,
        description='If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.',
    )
    error: Optional[Status] = Field(
        None,
        description='The error result of the operation in case of failure or cancellation.',
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description='An OperationMetadata or Metadata object. This will always be returned with the Operation.',
    )
    name: Optional[str] = Field(
        None,
        description='The server-assigned name, which is only unique within the same service that originally returns it. For example: `operations/CJHU7Oi_ChDrveSpBRjfuL-qzoWAgEw`',
    )
    response: Optional[Dict[str, Any]] = Field(None, description='An Empty object.')


class VirtualMachine(BaseModel):
    accelerators: Optional[List[Accelerator]] = Field(
        None, description='The list of accelerators to attach to the VM.'
    )
    bootDiskSizeGb: Optional[int] = Field(
        None,
        description='The size of the boot disk, in GB. The boot disk must be large enough to accommodate all of the Docker images from each action in the pipeline at the same time. If not specified, a small but reasonable default value is used.',
    )
    bootImage: Optional[str] = Field(
        None,
        description='The host operating system image to use. Currently, only Container-Optimized OS images can be used. The default value is `projects/cos-cloud/global/images/family/cos-stable`, which selects the latest stable release of Container-Optimized OS. This option is provided to allow testing against the beta release of the operating system to ensure that the new version does not interact negatively with production pipelines. To test a pipeline against the beta release of Container-Optimized OS, use the value `projects/cos-cloud/global/images/family/cos-beta`.',
    )
    cpuPlatform: Optional[str] = Field(
        None,
        description='The CPU platform to request. An instance based on a newer platform can be allocated, but never one with fewer capabilities. The value of this parameter must be a valid Compute Engine CPU platform name (such as "Intel Skylake"). This parameter is only useful for carefully optimized work loads where the CPU platform has a significant impact. For more information about the effect of this parameter, see https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform.',
    )
    disks: Optional[List[Disk]] = Field(
        None,
        description='The list of disks to create and attach to the VM. Specify either the `volumes[]` field or the `disks[]` field, but not both.',
    )
    dockerCacheImages: Optional[List[str]] = Field(
        None,
        description='The Compute Engine Disk Images to use as a Docker cache. The disks will be mounted into the Docker folder in a way that the images present in the cache will not need to be pulled. The digests of the cached images must match those of the tags used or the latest version will still be pulled. The root directory of the ext4 image must contain `image` and `overlay2` directories copied from the Docker directory of a VM where the desired Docker images have already been pulled. Any images pulled that are not cached will be stored on the first cache disk instead of the boot disk. Only a single image is supported.',
    )
    enableStackdriverMonitoring: Optional[bool] = Field(
        None, description='Whether Stackdriver monitoring should be enabled on the VM.'
    )
    labels: Optional[Dict[str, str]] = Field(
        None,
        description="Optional set of labels to apply to the VM and any attached disk resources. These labels must adhere to the [name and value restrictions](https://cloud.google.com/compute/docs/labeling-resources) on VM labels imposed by Compute Engine. Labels keys with the prefix 'google-' are reserved for use by Google. Labels applied at creation time to the VM. Applied on a best-effort basis to attached disk resources shortly after VM creation.",
    )
    machineType: Optional[str] = Field(
        None,
        description='Required. The machine type of the virtual machine to create. Must be the short name of a standard machine type (such as "n1-standard-1") or a custom machine type (such as "custom-1-4096", where "1" indicates the number of vCPUs and "4096" indicates the memory in MB). See [Creating an instance with a custom machine type](https://cloud.google.com/compute/docs/instances/creating-instance-with-custom-machine-type#create) for more specifications on creating a custom machine type.',
    )
    network: Optional[Network] = Field(
        None, description='The VM network configuration.'
    )
    nvidiaDriverVersion: Optional[str] = Field(
        None,
        description='The NVIDIA driver version to use when attaching an NVIDIA GPU accelerator. The version specified here must be compatible with the GPU libraries contained in the container being executed, and must be one of the drivers hosted in the `nvidia-drivers-us-public` bucket on Google Cloud Storage.',
    )
    preemptible: Optional[bool] = Field(
        None, description='If true, allocate a preemptible VM.'
    )
    reservation: Optional[str] = Field(
        None,
        description="If specified, the VM will only be allocated inside the matching reservation. It will fail if the VM parameters don't match the reservation.",
    )
    serviceAccount: Optional[ServiceAccount] = Field(
        None,
        description='The service account to install on the VM. This account does not need any permissions other than those required by the pipeline.',
    )
    volumes: Optional[List[Volume]] = Field(
        None,
        description='The list of disks and other storage to create or attach to the VM. Specify either the `volumes[]` field or the `disks[]` field, but not both.',
    )


class ListOperationsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None, description='The standard List next-page token.'
    )
    operations: Optional[List[Operation]] = Field(
        None,
        description='A list of operations that matches the specified filter in the request.',
    )


class Resources(BaseModel):
    projectId: Optional[str] = Field(
        None, description='The project ID to allocate resources in.'
    )
    regions: Optional[List[str]] = Field(
        None,
        description='The list of regions allowed for VM allocation. If set, the `zones` field must not be set.',
    )
    virtualMachine: Optional[VirtualMachine] = Field(
        None, description='The virtual machine specification.'
    )
    zones: Optional[List[str]] = Field(
        None,
        description='The list of zones allowed for VM allocation. If set, the `regions` field must not be set.',
    )


class Pipeline(BaseModel):
    actions: Optional[List[Action]] = Field(
        None,
        description='The list of actions to execute, in the order they are specified.',
    )
    encryptedEnvironment: Optional[Secret] = Field(
        None,
        description='The encrypted environment to pass into every action. Each action can also specify its own encrypted environment. The secret must decrypt to a JSON-encoded dictionary where key-value pairs serve as environment variable names and their values. The decoded environment variables can overwrite the values specified by the `environment` field.',
    )
    environment: Optional[Dict[str, str]] = Field(
        None,
        description='The environment to pass into every action. Each action can also specify additional environment variables but cannot delete an entry from this map (though they can overwrite it with a different value).',
    )
    resources: Optional[Resources] = Field(
        None, description='The resources required for execution.'
    )
    timeout: Optional[str] = Field(
        None,
        description='The maximum amount of time to give the pipeline to complete. This includes the time spent waiting for a worker to be allocated. If the pipeline fails to complete before the timeout, it will be cancelled and the error code will be set to DEADLINE_EXCEEDED. If unspecified, it will default to 7 days.',
    )


class RunPipelineRequest(BaseModel):
    labels: Optional[Dict[str, str]] = Field(
        None,
        description='User-defined labels to associate with the returned operation. These labels are not propagated to any Google Cloud Platform resources used by the operation, and can be modified at any time. To associate labels with resources created while executing the operation, see the appropriate resource message (for example, `VirtualMachine`).',
    )
    pipeline: Optional[Pipeline] = Field(
        None, description='Required. The description of the pipeline to run.'
    )
    pubSubTopic: Optional[str] = Field(
        None,
        description='The name of an existing Pub/Sub topic. The server will publish messages to this topic whenever the status of the operation changes. The Genomics Service Agent account must have publisher permissions to the specified topic or notifications will not be sent.',
    )


class Metadata(BaseModel):
    createTime: Optional[str] = Field(
        None, description='The time at which the operation was created by the API.'
    )
    endTime: Optional[str] = Field(
        None,
        description='The time at which execution was completed and resources were cleaned up.',
    )
    events: Optional[List[Event]] = Field(
        None,
        description='The list of events that have happened so far during the execution of this operation.',
    )
    labels: Optional[Dict[str, str]] = Field(
        None, description='The user-defined labels associated with this operation.'
    )
    pipeline: Optional[Pipeline] = Field(
        None, description='The pipeline this operation represents.'
    )
    startTime: Optional[str] = Field(
        None,
        description='The first time at which resources were allocated to execute the pipeline.',
    )
